<?php
$data = $block->getFormUrl();
?>
<form style="padding: 1rem; margin-top: 1rem; border: 1px solid silver" method="POST" action="<?php echo $block->getAddUrl() ?>" >
        <h3>Add new Employee</h3>
        <div>
            <label>Firstname</label>
            <input name="firstname" type="text" />
        </div>
        <div>
            <label> Lastname</label>
            <input name="lastname" type="text"/>
        </div>
        <div>
            <label>Email</label>
            <input name="email" type="text"/>
        </div>
        <div>
            <label>Mobile No</label>
            <input name="mobile" type="text"/>
        </div>
        <div>
            <label> Date of birth</label>
            <input name="date" type="date"/>
        </div>
        <div>
            <label>Address </label>
           <textarea name="address"></textarea>
        </div>
     <button>Add</button>
    </form>
</div>
